title: LLM Researcher & Quant
description: 大模型算法工程师 · 量化交易者 · Agent 方向
url: https://lvcc2018.github.io
author: Ethan Lu
email: thulvcc2017@gmail.com

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

defaults:
  - scope:
      path: "_posts"
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: page
