title: LLM Researcher & Quant
description: 大模型算法工程师 · LLM Agent · 量化交易
url: https://lvcc2018.github.io
author: Ethan Lu
email: thulvcc2017@gmail.com

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

defaults:
  - scope:
      path: "_posts"
    values:
      layout: post
  - scope:
      path: "index.md"
    values:
      layout: home
  - scope:
      path: ""
    values:
      layout: default
